# Auto-generated by build_locations.py. Do not edit manually.
LOCATIONS = {
    "An Giang": {
        "type": "province",
        "lat": 10.5,
        "lon": 105.25,
        "aliases": [
            "AN GIANG",
            "An Giang",
            "an giang"
        ]
    },
    "Bắc Ninh": {
        "type": "province",
        "lat": 21.183,
        "lon": 106.083,
        "aliases": [
            "BAC NINH",
            "BẮC NINH",
            "Bắc Ninh",
            "bac ninh",
            "bắc ninh"
        ]
    },
    "Cà Mau": {
        "type": "province",
        "lat": 9.05,
        "lon": 105.15,
        "aliases": [
            "CA MAU",
            "CÀ MAU",
            "Cà Mau",
            "ca mau",
            "cà mau"
        ]
    },
    "Cao Bằng": {
        "type": "province",
        "lat": 22.65,
        "lon": 106.25,
        "aliases": [
            "CAO BANG",
            "CAO BẰNG",
            "Cao Bằng",
            "cao bang",
            "cao bằng"
        ]
    },
    "TP. Cần Thơ": {
        "type": "province",
        "lat": 10.033,
        "lon": 105.783,
        "aliases": [
            "TP. CAN THO",
            "TP. CẦN THƠ",
            "TP. Cần Thơ",
            "tp. can tho",
            "tp. cần thơ"
        ]
    },
    "TP. Đà Nẵng": {
        "type": "province",
        "lat": 16.054407,
        "lon": 108.202167,
        "aliases": [
            "DANANG",
            "DN",
            "TP. ĐA NANG",
            "TP. ĐÀ NẴNG",
            "TP. Đà Nẵng",
            "danang",
            "dn",
            "tp. đa nang",
            "tp. đà nẵng"
        ]
    },
    "Đắk Lắk": {
        "type": "province",
        "lat": 12.833,
        "lon": 108.083,
        "aliases": [
            "ĐAK LAK",
            "ĐẮK LẮK",
            "Đắk Lắk",
            "đak lak",
            "đắk lắk"
        ]
    },
    "Điện Biên": {
        "type": "province",
        "lat": 21.383,
        "lon": 103.15,
        "aliases": [
            "ĐIEN BIEN",
            "ĐIỆN BIÊN",
            "Điện Biên",
            "đien bien",
            "điện biên"
        ]
    },
    "Đồng Nai": {
        "type": "province",
        "lat": 10.95,
        "lon": 106.816,
        "aliases": [
            "ĐONG NAI",
            "ĐỒNG NAI",
            "Đồng Nai",
            "đong nai",
            "đồng nai"
        ]
    },
    "Đồng Tháp": {
        "type": "province",
        "lat": 10.45,
        "lon": 105.633,
        "aliases": [
            "ĐONG THAP",
            "ĐỒNG THÁP",
            "Đồng Tháp",
            "đong thap",
            "đồng tháp"
        ]
    },
    "Gia Lai": {
        "type": "province",
        "lat": 13.983,
        "lon": 108.25,
        "aliases": [
            "GIA LAI",
            "Gia Lai",
            "gia lai"
        ]
    },
    "TP. Hà Nội": {
        "type": "province",
        "lat": 21.028511,
        "lon": 105.854444,
        "aliases": [
            "HANOI",
            "HN",
            "TP. HA NOI",
            "TP. HÀ NỘI",
            "TP. Hà Nội",
            "hanoi",
            "hn",
            "tp. ha noi",
            "tp. hà nội"
        ]
    },
    "Hà Tĩnh": {
        "type": "province",
        "lat": 18.333,
        "lon": 105.75,
        "aliases": [
            "HA TINH",
            "HÀ TĨNH",
            "Hà Tĩnh",
            "ha tinh",
            "hà tĩnh"
        ]
    },
    "TP. Hải Phòng": {
        "type": "province",
        "lat": 20.844911,
        "lon": 106.682035,
        "aliases": [
            "TP. HAI PHONG",
            "TP. HẢI PHÒNG",
            "TP. Hải Phòng",
            "tp. hai phong",
            "tp. hải phòng"
        ]
    },
    "TP. Hồ Chí Minh": {
        "type": "province",
        "lat": 10.762622,
        "lon": 106.660172,
        "aliases": [
            "HCM",
            "SAI GON",
            "SÀI GÒN",
            "TP. HO CHI MINH",
            "TP. HỒ CHÍ MINH",
            "TP. Hồ Chí Minh",
            "hcm",
            "sai gon",
            "sài gòn",
            "tp. ho chi minh",
            "tp. hồ chí minh"
        ]
    },
    "TP. Huế": {
        "type": "province",
        "lat": 16.467,
        "lon": 107.6,
        "aliases": [
            "TP. HUE",
            "TP. HUẾ",
            "TP. Huế",
            "tp. hue",
            "tp. huế"
        ]
    },
    "Hưng Yên": {
        "type": "province",
        "lat": 20.65,
        "lon": 106.083,
        "aliases": [
            "HUNG YEN",
            "HƯNG YÊN",
            "Hưng Yên",
            "hung yen",
            "hưng yên"
        ]
    },
    "Khánh Hòa": {
        "type": "province",
        "lat": 12.25,
        "lon": 109.083,
        "aliases": [
            "KHANH HOA",
            "KHÁNH HÒA",
            "Khánh Hòa",
            "khanh hoa",
            "khánh hòa"
        ]
    },
    "Lai Châu": {
        "type": "province",
        "lat": 22.383,
        "lon": 103.25,
        "aliases": [
            "LAI CHAU",
            "LAI CHÂU",
            "Lai Châu",
            "lai chau",
            "lai châu"
        ]
    },
    "Lâm Đồng": {
        "type": "province",
        "lat": 11.75,
        "lon": 108.333,
        "aliases": [
            "LAM ĐONG",
            "LÂM ĐỒNG",
            "Lâm Đồng",
            "lam đong",
            "lâm đồng"
        ]
    },
    "Lạng Sơn": {
        "type": "province",
        "lat": 21.833,
        "lon": 106.75,
        "aliases": [
            "LANG SON",
            "LẠNG SƠN",
            "Lạng Sơn",
            "lang son",
            "lạng sơn"
        ]
    },
    "Lào Cai": {
        "type": "province",
        "lat": 22.383,
        "lon": 104.083,
        "aliases": [
            "LAO CAI",
            "LÀO CAI",
            "Lào Cai",
            "lao cai",
            "lào cai"
        ]
    },
    "Nghệ An": {
        "type": "province",
        "lat": 19.2,
        "lon": 104.9,
        "aliases": [
            "NGHE AN",
            "NGHỆ AN",
            "Nghệ An",
            "nghe an",
            "nghệ an"
        ]
    },
    "Ninh Bình": {
        "type": "province",
        "lat": 20.25,
        "lon": 105.833,
        "aliases": [
            "NINH BINH",
            "NINH BÌNH",
            "Ninh Bình",
            "ninh binh",
            "ninh bình"
        ]
    },
    "Phú Thọ": {
        "type": "province",
        "lat": 21.3,
        "lon": 105.2,
        "aliases": [
            "PHU THO",
            "PHÚ THỌ",
            "Phú Thọ",
            "phu tho",
            "phú thọ"
        ]
    },
    "Quảng Ngãi": {
        "type": "province",
        "lat": 15.0,
        "lon": 108.8,
        "aliases": [
            "QUANG NGAI",
            "QUẢNG NGÃI",
            "Quảng Ngãi",
            "quang ngai",
            "quảng ngãi"
        ]
    },
    "Quảng Ninh": {
        "type": "province",
        "lat": 21.0,
        "lon": 107.083,
        "aliases": [
            "QUANG NINH",
            "QUẢNG NINH",
            "Quảng Ninh",
            "quang ninh",
            "quảng ninh"
        ]
    },
    "Quảng Trị": {
        "type": "province",
        "lat": 16.75,
        "lon": 107.0,
        "aliases": [
            "QUANG TRI",
            "QUẢNG TRỊ",
            "Quảng Trị",
            "quang tri",
            "quảng trị"
        ]
    },
    "Sơn La": {
        "type": "province",
        "lat": 21.0,
        "lon": 104.0,
        "aliases": [
            "SON LA",
            "SƠN LA",
            "Sơn La",
            "son la",
            "sơn la"
        ]
    },
    "Tây Ninh": {
        "type": "province",
        "lat": 11.333,
        "lon": 106.25,
        "aliases": [
            "TAY NINH",
            "TÂY NINH",
            "Tây Ninh",
            "tay ninh",
            "tây ninh"
        ]
    },
    "Thái Nguyên": {
        "type": "province",
        "lat": 21.6,
        "lon": 105.833,
        "aliases": [
            "THAI NGUYEN",
            "THÁI NGUYÊN",
            "Thái Nguyên",
            "thai nguyen",
            "thái nguyên"
        ]
    },
    "Thanh Hóa": {
        "type": "province",
        "lat": 19.8,
        "lon": 105.5,
        "aliases": [
            "THANH HOA",
            "THANH HÓA",
            "Thanh Hóa",
            "thanh hoa",
            "thanh hóa"
        ]
    },
    "Tuyên Quang": {
        "type": "province",
        "lat": 21.833,
        "lon": 105.25,
        "aliases": [
            "TUYEN QUANG",
            "TUYÊN QUANG",
            "Tuyên Quang",
            "tuyen quang",
            "tuyên quang"
        ]
    },
    "Vĩnh Long": {
        "type": "province",
        "lat": 10.25,
        "lon": 105.95,
        "aliases": [
            "VINH LONG",
            "VĨNH LONG",
            "Vĩnh Long",
            "vinh long",
            "vĩnh long"
        ]
    },
    "Phường Hải Châu": {
        "type": "ward",
        "lat": 16.0678,
        "lon": 108.22,
        "aliases": [
            "PHUONG HAI CHAU",
            "PHƯỜNG HẢI CHÂU",
            "Phường Hải Châu",
            "phuong hai chau",
            "phường hải châu"
        ]
    },
    "Phường Hòa Cường": {
        "type": "ward",
        "lat": 16.0678,
        "lon": 108.2225,
        "aliases": [
            "PHUONG HOA CUONG",
            "PHƯỜNG HÒA CƯỜNG",
            "Phường Hòa Cường",
            "phuong hoa cuong",
            "phường hòa cường"
        ]
    },
    "Phường Thanh Khê": {
        "type": "ward",
        "lat": 16.0678,
        "lon": 108.225,
        "aliases": [
            "PHUONG THANH KHE",
            "PHƯỜNG THANH KHÊ",
            "Phường Thanh Khê",
            "phuong thanh khe",
            "phường thanh khê"
        ]
    },
    "Phường An Khê": {
        "type": "ward",
        "lat": 16.0678,
        "lon": 108.2275,
        "aliases": [
            "PHUONG AN KHE",
            "PHƯỜNG AN KHÊ",
            "Phường An Khê",
            "phuong an khe",
            "phường an khê"
        ]
    },
    "Phường An Hải": {
        "type": "ward",
        "lat": 16.0678,
        "lon": 108.23,
        "aliases": [
            "PHUONG AN HAI",
            "PHƯỜNG AN HẢI",
            "Phường An Hải",
            "phuong an hai",
            "phường an hải"
        ]
    },
    "Phường Sơn Trà": {
        "type": "ward",
        "lat": 16.0678,
        "lon": 108.2325,
        "aliases": [
            "PHUONG SON TRA",
            "PHƯỜNG SƠN TRÀ",
            "Phường Sơn Trà",
            "phuong son tra",
            "phường sơn trà"
        ]
    },
    "Phường Ngũ Hành Sơn": {
        "type": "ward",
        "lat": 16.0678,
        "lon": 108.235,
        "aliases": [
            "PHUONG NGU HANH SON",
            "PHƯỜNG NGŨ HÀNH SƠN",
            "Phường Ngũ Hành Sơn",
            "phuong ngu hanh son",
            "phường ngũ hành sơn"
        ]
    },
    "Phường Hòa Khánh": {
        "type": "ward",
        "lat": 16.0678,
        "lon": 108.2375,
        "aliases": [
            "PHUONG HOA KHANH",
            "PHƯỜNG HÒA KHÁNH",
            "Phường Hòa Khánh",
            "phuong hoa khanh",
            "phường hòa khánh"
        ]
    },
    "Phường Hải Vân": {
        "type": "ward",
        "lat": 16.0678,
        "lon": 108.24,
        "aliases": [
            "PHUONG HAI VAN",
            "PHƯỜNG HẢI VÂN",
            "Phường Hải Vân",
            "phuong hai van",
            "phường hải vân"
        ]
    },
    "Phường Liên Chiểu": {
        "type": "ward",
        "lat": 16.0678,
        "lon": 108.2425,
        "aliases": [
            "PHUONG LIEN CHIEU",
            "PHƯỜNG LIÊN CHIỂU",
            "Phường Liên Chiểu",
            "phuong lien chieu",
            "phường liên chiểu"
        ]
    },
    "Phường Cẩm Lệ": {
        "type": "ward",
        "lat": 16.0698,
        "lon": 108.22,
        "aliases": [
            "PHUONG CAM LE",
            "PHƯỜNG CẨM LỆ",
            "Phường Cẩm Lệ",
            "phuong cam le",
            "phường cẩm lệ"
        ]
    },
    "Phường Hòa Xuân": {
        "type": "ward",
        "lat": 16.0698,
        "lon": 108.2225,
        "aliases": [
            "PHUONG HOA XUAN",
            "PHƯỜNG HÒA XUÂN",
            "Phường Hòa Xuân",
            "phuong hoa xuan",
            "phường hòa xuân"
        ]
    },
    "Phường Tam Kỳ": {
        "type": "ward",
        "lat": 16.0698,
        "lon": 108.225,
        "aliases": [
            "PHUONG TAM KY",
            "PHƯỜNG TAM KỲ",
            "Phường Tam Kỳ",
            "phuong tam ky",
            "phường tam kỳ"
        ]
    },
    "Phường Quảng Phú": {
        "type": "ward",
        "lat": 16.0698,
        "lon": 108.2275,
        "aliases": [
            "PHUONG QUANG PHU",
            "PHƯỜNG QUẢNG PHÚ",
            "Phường Quảng Phú",
            "phuong quang phu",
            "phường quảng phú"
        ]
    },
    "Phường Hương Trà": {
        "type": "ward",
        "lat": 16.0698,
        "lon": 108.23,
        "aliases": [
            "PHUONG HUONG TRA",
            "PHƯỜNG HƯƠNG TRÀ",
            "Phường Hương Trà",
            "phuong huong tra",
            "phường hương trà"
        ]
    },
    "Phường Bàn Thạch": {
        "type": "ward",
        "lat": 16.0698,
        "lon": 108.2325,
        "aliases": [
            "PHUONG BAN THACH",
            "PHƯỜNG BÀN THẠCH",
            "Phường Bàn Thạch",
            "phuong ban thach",
            "phường bàn thạch"
        ]
    },
    "Phường Điện Bàn": {
        "type": "ward",
        "lat": 16.0698,
        "lon": 108.235,
        "aliases": [
            "PHUONG ĐIEN BAN",
            "PHƯỜNG ĐIỆN BÀN",
            "Phường Điện Bàn",
            "phuong đien ban",
            "phường điện bàn"
        ]
    },
    "Phường Điện Bàn Đông": {
        "type": "ward",
        "lat": 16.0698,
        "lon": 108.2375,
        "aliases": [
            "PHUONG ĐIEN BAN ĐONG",
            "PHƯỜNG ĐIỆN BÀN ĐÔNG",
            "Phường Điện Bàn Đông",
            "phuong đien ban đong",
            "phường điện bàn đông"
        ]
    },
    "Phường An Thắng": {
        "type": "ward",
        "lat": 16.0698,
        "lon": 108.24,
        "aliases": [
            "PHUONG AN THANG",
            "PHƯỜNG AN THẮNG",
            "Phường An Thắng",
            "phuong an thang",
            "phường an thắng"
        ]
    },
    "Phường Điện Bàn Bắc": {
        "type": "ward",
        "lat": 16.0698,
        "lon": 108.2425,
        "aliases": [
            "PHUONG ĐIEN BAN BAC",
            "PHƯỜNG ĐIỆN BÀN BẮC",
            "Phường Điện Bàn Bắc",
            "phuong đien ban bac",
            "phường điện bàn bắc"
        ]
    },
    "Phường Hội An": {
        "type": "ward",
        "lat": 16.0718,
        "lon": 108.22,
        "aliases": [
            "PHUONG HOI AN",
            "PHƯỜNG HỘI AN",
            "Phường Hội An",
            "phuong hoi an",
            "phường hội an"
        ]
    },
    "Phường Hội An Đông": {
        "type": "ward",
        "lat": 16.0718,
        "lon": 108.2225,
        "aliases": [
            "PHUONG HOI AN ĐONG",
            "PHƯỜNG HỘI AN ĐÔNG",
            "Phường Hội An Đông",
            "phuong hoi an đong",
            "phường hội an đông"
        ]
    },
    "Phường Hội An Tây": {
        "type": "ward",
        "lat": 16.0718,
        "lon": 108.225,
        "aliases": [
            "PHUONG HOI AN TAY",
            "PHƯỜNG HỘI AN TÂY",
            "Phường Hội An Tây",
            "phuong hoi an tay",
            "phường hội an tây"
        ]
    },
    "Xã Hòa Vang": {
        "type": "ward",
        "lat": 16.0718,
        "lon": 108.2275,
        "aliases": [
            "XA HOA VANG",
            "XÃ HÒA VANG",
            "Xã Hòa Vang",
            "xa hoa vang",
            "xã hòa vang"
        ]
    },
    "Xã Hòa Tiến": {
        "type": "ward",
        "lat": 16.0718,
        "lon": 108.23,
        "aliases": [
            "XA HOA TIEN",
            "XÃ HÒA TIẾN",
            "Xã Hòa Tiến",
            "xa hoa tien",
            "xã hòa tiến"
        ]
    },
    "Xã Bà Nà": {
        "type": "ward",
        "lat": 16.0718,
        "lon": 108.2325,
        "aliases": [
            "XA BA NA",
            "XÃ BÀ NÀ",
            "Xã Bà Nà",
            "xa ba na",
            "xã bà nà"
        ]
    },
    "Xã Núi Thành": {
        "type": "ward",
        "lat": 16.0718,
        "lon": 108.235,
        "aliases": [
            "XA NUI THANH",
            "XÃ NÚI THÀNH",
            "Xã Núi Thành",
            "xa nui thanh",
            "xã núi thành"
        ]
    },
    "Xã Tam Mỹ": {
        "type": "ward",
        "lat": 16.0718,
        "lon": 108.2375,
        "aliases": [
            "XA TAM MY",
            "XÃ TAM MỸ",
            "Xã Tam Mỹ",
            "xa tam my",
            "xã tam mỹ"
        ]
    },
    "Xã Tam Anh": {
        "type": "ward",
        "lat": 16.0718,
        "lon": 108.24,
        "aliases": [
            "XA TAM ANH",
            "XÃ TAM ANH",
            "Xã Tam Anh",
            "xa tam anh",
            "xã tam anh"
        ]
    },
    "Xã Đức Phú": {
        "type": "ward",
        "lat": 16.0718,
        "lon": 108.2425,
        "aliases": [
            "XA ĐUC PHU",
            "XÃ ĐỨC PHÚ",
            "Xã Đức Phú",
            "xa đuc phu",
            "xã đức phú"
        ]
    },
    "Xã Tam Xuân": {
        "type": "ward",
        "lat": 16.0738,
        "lon": 108.22,
        "aliases": [
            "XA TAM XUAN",
            "XÃ TAM XUÂN",
            "Xã Tam Xuân",
            "xa tam xuan",
            "xã tam xuân"
        ]
    },
    "Xã Tây Hồ": {
        "type": "ward",
        "lat": 16.0738,
        "lon": 108.2225,
        "aliases": [
            "XA TAY HO",
            "XÃ TÂY HỒ",
            "Xã Tây Hồ",
            "xa tay ho",
            "xã tây hồ"
        ]
    },
    "Xã Chiên Đàn": {
        "type": "ward",
        "lat": 16.0738,
        "lon": 108.225,
        "aliases": [
            "XA CHIEN ĐAN",
            "XÃ CHIÊN ĐÀN",
            "Xã Chiên Đàn",
            "xa chien đan",
            "xã chiên đàn"
        ]
    },
    "Xã Phú Ninh": {
        "type": "ward",
        "lat": 16.0738,
        "lon": 108.2275,
        "aliases": [
            "XA PHU NINH",
            "XÃ PHÚ NINH",
            "Xã Phú Ninh",
            "xa phu ninh",
            "xã phú ninh"
        ]
    },
    "Xã Lãnh Ngọc": {
        "type": "ward",
        "lat": 15.424678,
        "lon": 108.2618422,
        "aliases": [
            "XA LANH NGOC",
            "XÃ LÃNH NGỌC",
            "Xã Lãnh Ngọc",
            "xa lanh ngoc",
            "xã lãnh ngọc"
        ]
    },
    "Xã Tiên Phước": {
        "type": "ward",
        "lat": 16.0738,
        "lon": 108.2325,
        "aliases": [
            "XA TIEN PHUOC",
            "XÃ TIÊN PHƯỚC",
            "Xã Tiên Phước",
            "xa tien phuoc",
            "xã tiên phước"
        ]
    },
    "Xã Thạnh Bình": {
        "type": "ward",
        "lat": 16.0738,
        "lon": 108.235,
        "aliases": [
            "XA THANH BINH",
            "XÃ THẠNH BÌNH",
            "Xã Thạnh Bình",
            "xa thanh binh",
            "xã thạnh bình"
        ]
    },
    "Xã Sơn Cẩm Hà": {
        "type": "ward",
        "lat": 16.0738,
        "lon": 108.2375,
        "aliases": [
            "XA SON CAM HA",
            "XÃ SƠN CẨM HÀ",
            "Xã Sơn Cẩm Hà",
            "xa son cam ha",
            "xã sơn cẩm hà"
        ]
    },
    "Xã Trà Liên": {
        "type": "ward",
        "lat": 16.0738,
        "lon": 108.24,
        "aliases": [
            "XA TRA LIEN",
            "XÃ TRÀ LIÊN",
            "Xã Trà Liên",
            "xa tra lien",
            "xã trà liên"
        ]
    },
    "Xã Trà Giáp": {
        "type": "ward",
        "lat": 16.0738,
        "lon": 108.2425,
        "aliases": [
            "XA TRA GIAP",
            "XÃ TRÀ GIÁP",
            "Xã Trà Giáp",
            "xa tra giap",
            "xã trà giáp"
        ]
    },
    "Xã Trà Tân": {
        "type": "ward",
        "lat": 16.0758,
        "lon": 108.22,
        "aliases": [
            "XA TRA TAN",
            "XÃ TRÀ TÂN",
            "Xã Trà Tân",
            "xa tra tan",
            "xã trà tân"
        ]
    },
    "Xã Trà Đốc": {
        "type": "ward",
        "lat": 16.0758,
        "lon": 108.2225,
        "aliases": [
            "XA TRA ĐOC",
            "XÃ TRÀ ĐỐC",
            "Xã Trà Đốc",
            "xa tra đoc",
            "xã trà đốc"
        ]
    },
    "Xã Trà My": {
        "type": "ward",
        "lat": 16.0758,
        "lon": 108.225,
        "aliases": [
            "XA TRA MY",
            "XÃ TRÀ MY",
            "Xã Trà My",
            "xa tra my",
            "xã trà my"
        ]
    },
    "Xã Nam Trà My": {
        "type": "ward",
        "lat": 16.0758,
        "lon": 108.2275,
        "aliases": [
            "XA NAM TRA MY",
            "XÃ NAM TRÀ MY",
            "Xã Nam Trà My",
            "xa nam tra my",
            "xã nam trà my"
        ]
    },
    "Xã Trà Tập": {
        "type": "ward",
        "lat": 16.0758,
        "lon": 108.23,
        "aliases": [
            "XA TRA TAP",
            "XÃ TRÀ TẬP",
            "Xã Trà Tập",
            "xa tra tap",
            "xã trà tập"
        ]
    },
    "Xã Trà Vân": {
        "type": "ward",
        "lat": 16.0758,
        "lon": 108.2325,
        "aliases": [
            "XA TRA VAN",
            "XÃ TRÀ VÂN",
            "Xã Trà Vân",
            "xa tra van",
            "xã trà vân"
        ]
    },
    "Xã Trà Linh": {
        "type": "ward",
        "lat": 16.0758,
        "lon": 108.235,
        "aliases": [
            "XA TRA LINH",
            "XÃ TRÀ LINH",
            "Xã Trà Linh",
            "xa tra linh",
            "xã trà linh"
        ]
    },
    "Xã Trà Leng": {
        "type": "ward",
        "lat": 16.0758,
        "lon": 108.2375,
        "aliases": [
            "XA TRA LENG",
            "XÃ TRÀ LENG",
            "Xã Trà Leng",
            "xa tra leng",
            "xã trà leng"
        ]
    },
    "Xã Thăng Bình": {
        "type": "ward",
        "lat": 16.0758,
        "lon": 108.24,
        "aliases": [
            "XA THANG BINH",
            "XÃ THĂNG BÌNH",
            "Xã Thăng Bình",
            "xa thang binh",
            "xã thăng bình"
        ]
    },
    "Xã Thăng An": {
        "type": "ward",
        "lat": 16.0758,
        "lon": 108.2425,
        "aliases": [
            "XA THANG AN",
            "XÃ THĂNG AN",
            "Xã Thăng An",
            "xa thang an",
            "xã thăng an"
        ]
    },
    "Xã Thăng Trường": {
        "type": "ward",
        "lat": 16.0778,
        "lon": 108.22,
        "aliases": [
            "XA THANG TRUONG",
            "XÃ THĂNG TRƯỜNG",
            "Xã Thăng Trường",
            "xa thang truong",
            "xã thăng trường"
        ]
    },
    "Xã Thăng Điền": {
        "type": "ward",
        "lat": 16.0778,
        "lon": 108.2225,
        "aliases": [
            "XA THANG ĐIEN",
            "XÃ THĂNG ĐIỀN",
            "Xã Thăng Điền",
            "xa thang đien",
            "xã thăng điền"
        ]
    },
    "Xã Thăng Phú": {
        "type": "ward",
        "lat": 16.0778,
        "lon": 108.225,
        "aliases": [
            "XA THANG PHU",
            "XÃ THĂNG PHÚ",
            "Xã Thăng Phú",
            "xa thang phu",
            "xã thăng phú"
        ]
    },
    "Xã Đồng Dương": {
        "type": "ward",
        "lat": 16.0778,
        "lon": 108.2275,
        "aliases": [
            "XA ĐONG DUONG",
            "XÃ ĐỒNG DƯƠNG",
            "Xã Đồng Dương",
            "xa đong duong",
            "xã đồng dương"
        ]
    },
    "Xã Quế Sơn Trung": {
        "type": "ward",
        "lat": 16.0778,
        "lon": 108.23,
        "aliases": [
            "XA QUE SON TRUNG",
            "XÃ QUẾ SƠN TRUNG",
            "Xã Quế Sơn Trung",
            "xa que son trung",
            "xã quế sơn trung"
        ]
    },
    "Xã Quế Sơn": {
        "type": "ward",
        "lat": 16.0778,
        "lon": 108.2325,
        "aliases": [
            "XA QUE SON",
            "XÃ QUẾ SƠN",
            "Xã Quế Sơn",
            "xa que son",
            "xã quế sơn"
        ]
    },
    "Xã Xuân Phú": {
        "type": "ward",
        "lat": 16.0778,
        "lon": 108.235,
        "aliases": [
            "XA XUAN PHU",
            "XÃ XUÂN PHÚ",
            "Xã Xuân Phú",
            "xa xuan phu",
            "xã xuân phú"
        ]
    },
    "Xã Nông Sơn": {
        "type": "ward",
        "lat": 16.0778,
        "lon": 108.2375,
        "aliases": [
            "XA NONG SON",
            "XÃ NÔNG SƠN",
            "Xã Nông Sơn",
            "xa nong son",
            "xã nông sơn"
        ]
    },
    "Xã Quế Phước": {
        "type": "ward",
        "lat": 16.0778,
        "lon": 108.24,
        "aliases": [
            "XA QUE PHUOC",
            "XÃ QUẾ PHƯỚC",
            "Xã Quế Phước",
            "xa que phuoc",
            "xã quế phước"
        ]
    },
    "Xã Duy Nghĩa": {
        "type": "ward",
        "lat": 16.0778,
        "lon": 108.2425,
        "aliases": [
            "XA DUY NGHIA",
            "XÃ DUY NGHĨA",
            "Xã Duy Nghĩa",
            "xa duy nghia",
            "xã duy nghĩa"
        ]
    },
    "Xã Nam Phước": {
        "type": "ward",
        "lat": 16.0798,
        "lon": 108.22,
        "aliases": [
            "XA NAM PHUOC",
            "XÃ NAM PHƯỚC",
            "Xã Nam Phước",
            "xa nam phuoc",
            "xã nam phước"
        ]
    },
    "Xã Duy Xuyên": {
        "type": "ward",
        "lat": 16.0798,
        "lon": 108.2225,
        "aliases": [
            "XA DUY XUYEN",
            "XÃ DUY XUYÊN",
            "Xã Duy Xuyên",
            "xa duy xuyen",
            "xã duy xuyên"
        ]
    },
    "Xã Thu Bồn": {
        "type": "ward",
        "lat": 16.0798,
        "lon": 108.225,
        "aliases": [
            "XA THU BON",
            "XÃ THU BỒN",
            "Xã Thu Bồn",
            "xa thu bon",
            "xã thu bồn"
        ]
    },
    "Xã Điện Bàn Tây": {
        "type": "ward",
        "lat": 16.0798,
        "lon": 108.2275,
        "aliases": [
            "XA ĐIEN BAN TAY",
            "XÃ ĐIỆN BÀN TÂY",
            "Xã Điện Bàn Tây",
            "xa đien ban tay",
            "xã điện bàn tây"
        ]
    },
    "Xã Gò Nổi": {
        "type": "ward",
        "lat": 16.0798,
        "lon": 108.23,
        "aliases": [
            "XA GO NOI",
            "XÃ GÒ NỔI",
            "Xã Gò Nổi",
            "xa go noi",
            "xã gò nổi"
        ]
    },
    "Xã Đại Lộc": {
        "type": "ward",
        "lat": 16.0798,
        "lon": 108.2325,
        "aliases": [
            "XA ĐAI LOC",
            "XÃ ĐẠI LỘC",
            "Xã Đại Lộc",
            "xa đai loc",
            "xã đại lộc"
        ]
    },
    "Xã Hà Nha": {
        "type": "ward",
        "lat": 16.0798,
        "lon": 108.235,
        "aliases": [
            "XA HA NHA",
            "XÃ HÀ NHA",
            "Xã Hà Nha",
            "xa ha nha",
            "xã hà nha"
        ]
    },
    "Xã Thượng Đức": {
        "type": "ward",
        "lat": 16.0798,
        "lon": 108.2375,
        "aliases": [
            "XA THUONG ĐUC",
            "XÃ THƯỢNG ĐỨC",
            "Xã Thượng Đức",
            "xa thuong đuc",
            "xã thượng đức"
        ]
    },
    "Xã Vu Gia": {
        "type": "ward",
        "lat": 16.0798,
        "lon": 108.24,
        "aliases": [
            "XA VU GIA",
            "XÃ VU GIA",
            "Xã Vu Gia",
            "xa vu gia",
            "xã vu gia"
        ]
    },
    "Xã Phú Thuận": {
        "type": "ward",
        "lat": 16.0798,
        "lon": 108.2425,
        "aliases": [
            "XA PHU THUAN",
            "XÃ PHÚ THUẬN",
            "Xã Phú Thuận",
            "xa phu thuan",
            "xã phú thuận"
        ]
    },
    "Xã Thạnh Mỹ": {
        "type": "ward",
        "lat": 16.0818,
        "lon": 108.22,
        "aliases": [
            "XA THANH MY",
            "XÃ THẠNH MỸ",
            "Xã Thạnh Mỹ",
            "xa thanh my",
            "xã thạnh mỹ"
        ]
    },
    "Xã Bến Giằng": {
        "type": "ward",
        "lat": 16.0818,
        "lon": 108.2225,
        "aliases": [
            "XA BEN GIANG",
            "XÃ BẾN GIẰNG",
            "Xã Bến Giằng",
            "xa ben giang",
            "xã bến giằng"
        ]
    },
    "Xã Nam Giang": {
        "type": "ward",
        "lat": 16.0818,
        "lon": 108.225,
        "aliases": [
            "XA NAM GIANG",
            "XÃ NAM GIANG",
            "Xã Nam Giang",
            "xa nam giang",
            "xã nam giang"
        ]
    },
    "Xã Đắc Pring": {
        "type": "ward",
        "lat": 16.0818,
        "lon": 108.2275,
        "aliases": [
            "XA ĐAC PRING",
            "XÃ ĐẮC PRING",
            "Xã Đắc Pring",
            "xa đac pring",
            "xã đắc pring"
        ]
    },
    "Xã La Dêê": {
        "type": "ward",
        "lat": 16.0818,
        "lon": 108.23,
        "aliases": [
            "XA LA DEE",
            "XÃ LA DÊÊ",
            "Xã La Dêê",
            "xa la dee",
            "xã la dêê"
        ]
    },
    "Xã La Êê": {
        "type": "ward",
        "lat": 16.0818,
        "lon": 108.2325,
        "aliases": [
            "XA LA EE",
            "XÃ LA ÊÊ",
            "Xã La Êê",
            "xa la ee",
            "xã la êê"
        ]
    },
    "Xã Sông Vàng": {
        "type": "ward",
        "lat": 16.0818,
        "lon": 108.235,
        "aliases": [
            "XA SONG VANG",
            "XÃ SÔNG VÀNG",
            "Xã Sông Vàng",
            "xa song vang",
            "xã sông vàng"
        ]
    },
    "Xã Sông Kôn": {
        "type": "ward",
        "lat": 16.0818,
        "lon": 108.2375,
        "aliases": [
            "XA SONG KON",
            "XÃ SÔNG KÔN",
            "Xã Sông Kôn",
            "xa song kon",
            "xã sông kôn"
        ]
    },
    "Xã Đông Giang": {
        "type": "ward",
        "lat": 16.0818,
        "lon": 108.24,
        "aliases": [
            "XA ĐONG GIANG",
            "XÃ ĐÔNG GIANG",
            "Xã Đông Giang",
            "xa đong giang",
            "xã đông giang"
        ]
    },
    "Xã Bến Hiên": {
        "type": "ward",
        "lat": 16.0818,
        "lon": 108.2425,
        "aliases": [
            "XA BEN HIEN",
            "XÃ BẾN HIÊN",
            "Xã Bến Hiên",
            "xa ben hien",
            "xã bến hiên"
        ]
    },
    "Xã Avương": {
        "type": "ward",
        "lat": 16.0838,
        "lon": 108.22,
        "aliases": [
            "XA AVUONG",
            "XÃ AVƯƠNG",
            "Xã Avương",
            "xa avuong",
            "xã avương"
        ]
    },
    "Xã Tây Giang": {
        "type": "ward",
        "lat": 16.0838,
        "lon": 108.2225,
        "aliases": [
            "XA TAY GIANG",
            "XÃ TÂY GIANG",
            "Xã Tây Giang",
            "xa tay giang",
            "xã tây giang"
        ]
    },
    "Xã Hùng Sơn": {
        "type": "ward",
        "lat": 16.0838,
        "lon": 108.225,
        "aliases": [
            "XA HUNG SON",
            "XÃ HÙNG SƠN",
            "Xã Hùng Sơn",
            "xa hung son",
            "xã hùng sơn"
        ]
    },
    "Xã Hiệp Đức": {
        "type": "ward",
        "lat": 16.0838,
        "lon": 108.2275,
        "aliases": [
            "XA HIEP ĐUC",
            "XÃ HIỆP ĐỨC",
            "Xã Hiệp Đức",
            "xa hiep đuc",
            "xã hiệp đức"
        ]
    },
    "Xã Việt An": {
        "type": "ward",
        "lat": 16.0838,
        "lon": 108.23,
        "aliases": [
            "XA VIET AN",
            "XÃ VIỆT AN",
            "Xã Việt An",
            "xa viet an",
            "xã việt an"
        ]
    },
    "Xã Phước Trà": {
        "type": "ward",
        "lat": 16.0838,
        "lon": 108.2325,
        "aliases": [
            "XA PHUOC TRA",
            "XÃ PHƯỚC TRÀ",
            "Xã Phước Trà",
            "xa phuoc tra",
            "xã phước trà"
        ]
    },
    "Xã Khâm Đức": {
        "type": "ward",
        "lat": 16.0838,
        "lon": 108.235,
        "aliases": [
            "XA KHAM ĐUC",
            "XÃ KHÂM ĐỨC",
            "Xã Khâm Đức",
            "xa kham đuc",
            "xã khâm đức"
        ]
    },
    "Xã Phước Năng": {
        "type": "ward",
        "lat": 16.0838,
        "lon": 108.2375,
        "aliases": [
            "XA PHUOC NANG",
            "XÃ PHƯỚC NĂNG",
            "Xã Phước Năng",
            "xa phuoc nang",
            "xã phước năng"
        ]
    },
    "Xã Phước Chánh": {
        "type": "ward",
        "lat": 16.0838,
        "lon": 108.24,
        "aliases": [
            "XA PHUOC CHANH",
            "XÃ PHƯỚC CHÁNH",
            "Xã Phước Chánh",
            "xa phuoc chanh",
            "xã phước chánh"
        ]
    },
    "Xã Phước Thành": {
        "type": "ward",
        "lat": 16.0838,
        "lon": 108.2425,
        "aliases": [
            "XA PHUOC THANH",
            "XÃ PHƯỚC THÀNH",
            "Xã Phước Thành",
            "xa phuoc thanh",
            "xã phước thành"
        ]
    },
    "Xã Phước Hiệp": {
        "type": "ward",
        "lat": 16.0858,
        "lon": 108.22,
        "aliases": [
            "XA PHUOC HIEP",
            "XÃ PHƯỚC HIỆP",
            "Xã Phước Hiệp",
            "xa phuoc hiep",
            "xã phước hiệp"
        ]
    },
    "Đặc khu Hoàng Sa": {
        "type": "ward",
        "lat": 16.0858,
        "lon": 108.2225,
        "aliases": [
            "ĐAC KHU HOANG SA",
            "ĐẶC KHU HOÀNG SA",
            "Đặc khu Hoàng Sa",
            "đac khu hoang sa",
            "đặc khu hoàng sa"
        ]
    },
    "Xã Tam Hải": {
        "type": "ward",
        "lat": 16.0858,
        "lon": 108.225,
        "aliases": [
            "XA TAM HAI",
            "XÃ TAM HẢI",
            "Xã Tam Hải",
            "xa tam hai",
            "xã tam hải"
        ]
    },
    "Xã Tân Hiệp": {
        "type": "ward",
        "lat": 16.0858,
        "lon": 108.2275,
        "aliases": [
            "XA TAN HIEP",
            "XÃ TÂN HIỆP",
            "Xã Tân Hiệp",
            "xa tan hiep",
            "xã tân hiệp"
        ]
    }
}